project:
  type: book
  output-dir: docs
  
book:
  title: "Байесовский спринт"
  author: "Г. А. Мороз"
  language: ru
  repo-url: https://github.com/agricolamz/2026.07.02_bayes_sprint/
  chapters:
    - index.qmd
    - 01-materials.qmd
    - 02-distributions.qmd
    - 03-likelihood.qmd
    - 04-intro-to-Bayes.qmd
    - 05-confidence-intervals.qmd
    - 06-Bayes-factor.qmd
    - 07-Introduction-to-MCMC.qmd
    - 08-introduction_to_bayesian_regression_with_brms.qmd
    - 09-Empirical-Bayes.qmd
    
execute:
  freeze: auto

callout-appearance: simple
callout-icon: false
bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    df-print: paged
